### ISSUE TITLE
Baixar os artigos

### ISSUE THREAD

**Issue by PedroBSB** [lamfo-unb/KernelPCA#1]
Vamos procurar no Google Scholar todos os artigos que citem RANDOM MATRIX THEORY AND FINANCIAL CORRELATIONS.

**Comment by lorebueno** [comment]
Bom dia Pedro!
Por favor me indica em qual diretório eu devo colocar os artigos.

abs

**Comment by PedroBSB** [comment]
Oi @lorebueno, se você já clonou o repositório pode criar qualquer pasta e coloca. Caso não tenha feito, ou esteja com dificuldade me avise que eu te mostro como fazer no Rstudio.
