### ISSUE TITLE
Fazer revisão dos artigos - 23/02/2018

### ISSUE THREAD

**Issue by PedroBSB** [lamfo-unb/KernelPCA#2]
Para cada artigo sleecionado pela @lorebueno verificar se tratam de Portfólio e a abordagem de PCA. Após a seleção escrever os parágrafos em Inglês (para cada artigo) respondendo:
1) Quem fez ?
2) Quando fez ?
3) Por que fez ?
4) Que métodos usou ?
5) Resultados ?
6) Limitações e inovação da proposta ?
7) Qual o campo de finanças ? Ativos e anos de estudo ?

**Comment by lorebueno** [comment]
@joaofm91  a pasta de artigos já está disponível!

**Comment by PedroBSB** [comment]
@joaofm91 por favor, atualize o artigo no overleaf com as revisões que você já fez.
Qualquer dúvida me procure.

**Comment by joaofm91** [comment]
Estou adicionando direto ao Overleaf. Segunda continuo adicionando pois viajo quinta, professor! Pode mandar feedback se preferir no próprio overleaf em comentário...

**Comment by PedroAMBH** [comment]
Lore adicionada para trabalhar na construcao do referencial teorico

**Comment by PedroAMBH** [comment]
Buscar:
- PCA financas,
- Kernel PCA.
- Relaçao entere eles.

**Comment by pengyaohao** [comment]
@joaofm91 principais bullet points a serem cobertos no referencial:

- PCA linear e limitações/motivação do kernel PCA [ver  **Linear dimensionality reduction: survey, insights, and generalizations.
JP Cunningham, Z Ghahramani**; **Randomized nonlinear component analysis
D Lopez-Paz, S Sra, A Smola, Z Ghahramani**]
- aplicações do kernel PCA em variadas áreas do conhecimento [ver **Kernel PCA for novelty detection
H Hoffmann**; **A survey of kernel and spectral methods for clustering
M Filippone, F Camastra, F Masulli, S Rovetta**;  **A Survey: Linear and Nonlinear PCA Based Face Recognition Techniques.
JH Shah, M Sharif, M Raza, A Azeem**; **Kernel association for classification and prediction: A survey
Y Motai**; **Identity management based on PCA and SVM
L Shen, H Wang, L Da Xu, X Ma, S Chaudhry**]
- redução de dimensionalidade em finanças [ver **Kozak, Serhiy and Nagel, Stefan and Santosh, Shrihari: Shrinking the Cross Section**; **A hybrid classifier based on nonlinear-PCA and deep belief networks with applications in dysphagia diagnosis
C Su, Y Gao, Y Xie, Y Xue, L Ge, H Li - Computer Assisted Surgery**; **Assessing regional sustainable development through an integration of nonlinear principal component analysis and Gram Schmidt orthogonalization
F Tan, Z Lu - Ecological Indicators**]
- Não-linearidade em finanças -- superioridade de modelos machine learning [ver **Hsu et al.: Bridging the divide in financial market forecasting: machine learners vs. financial economists**]
- Kernel PCA em finanças: o que tem sido feito? [ver **A kernel entropy manifold learning approach for financial data analysis
Y Huang, G Kou**; **A SVM stock selection model within PCA
H Yu, R Chen, G Zhang**]
