### ISSUE TITLE
Base de Dados - Ajustes - 17/03/2018

### ISSUE THREAD

**Issue by JuliaAkaishi** [lamfo-unb/KernelPCA#3]
Montar a base de dados com os ativos SP&500 e Nasdaq 2000 a 2017.

**Comment by pengyaohao** [comment]
Prorrogada para 02/03/2018

**Comment by pengyaohao** [comment]
Dados alta frequência para 17/03/2018

**Comment by igorfnasc** [comment]
finalizado
